# Generated by Django 6.0.6 on 2026-06-05 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Paciente')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Telefone/WhatsApp')),
                ('status', models.CharField(choices=[('atendimento', 'Em Atendimento'), ('aguardando_decisao', 'Aguardando Decisão'), ('agendado', 'Agendado'), ('perdido', 'Perdido'), ('reativacao', 'Reativação')], default='atendimento', max_length=50, verbose_name='Status')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Última Interação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Recebida (Paciente)'), ('out', 'Enviada (Clínica/IA)')], max_length=10, verbose_name='Direção')),
                ('content', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('atendimento', 'Em Atendimento'), ('aguardando_decisao', 'Aguardando Decisão'), ('agendado', 'Agendado'), ('perdido', 'Perdido'), ('reativacao', 'Reativação')], max_length=50, verbose_name='Status Anterior')),
                ('new_status', models.CharField(choices=[('atendimento', 'Em Atendimento'), ('aguardando_decisao', 'Aguardando Decisão'), ('agendado', 'Agendado'), ('perdido', 'Perdido'), ('reativacao', 'Reativação')], max_length=50, verbose_name='Novo Status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-changed_at'],
            },
        ),
    ]
