# Generated by Django 6.0.6 on 2026-06-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='followup_stage',
            field=models.IntegerField(default=0, verbose_name='Estágio de Follow-Up'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_followup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Follow-Up em'),
        ),
    ]
