# Generated by Django 6.0.3 on 2026-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_followup_stage_lead_last_followup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
