# Generated by Django 6.0.3 on 2026-06-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
