# Generated by Django 6.0.3 on 2026-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='chatwoot_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID no Chatwoot'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_followup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próximo Follow-up'),
        ),
        migrations.AddField(
            model_name='lead',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Estimado (R$)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do Lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo_lead', 'Novo Lead'), ('qualificacao', 'Em Qualificação'), ('orcamento', 'Orçamento Enviado'), ('agendado', 'Consulta Agendada'), ('em_tratamento', 'Em Tratamento'), ('ganho', 'Tratamento Concluído'), ('perdido', 'Perdido / Não Converteu')], default='novo_lead', max_length=50, verbose_name='Status/Etapa'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('novo_lead', 'Novo Lead'), ('qualificacao', 'Em Qualificação'), ('orcamento', 'Orçamento Enviado'), ('agendado', 'Consulta Agendada'), ('em_tratamento', 'Em Tratamento'), ('ganho', 'Tratamento Concluído'), ('perdido', 'Perdido / Não Converteu')], max_length=50, verbose_name='Novo Status'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.CharField(choices=[('novo_lead', 'Novo Lead'), ('qualificacao', 'Em Qualificação'), ('orcamento', 'Orçamento Enviado'), ('agendado', 'Consulta Agendada'), ('em_tratamento', 'Em Tratamento'), ('ganho', 'Tratamento Concluído'), ('perdido', 'Perdido / Não Converteu')], max_length=50, verbose_name='Status Anterior'),
        ),
    ]
